security: Fix AES-GCM JCE mode
AES-GCM is a stream cipher, so it doesn't need padding. Newer JVMs are
more strict about this:

javax.crypto.NoSuchPaddingException: GCM mode must be used with NoPadding
	at java.base/com.sun.crypto.provider.CipherCore.setPadding(CipherCore.java:341)
	at java.base/com.sun.crypto.provider.AESCipher.engineSetPadding(AESCipher.java:212)
	at java.base/javax.crypto.Cipher$Transform.setModePadding(Cipher.java:388)
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:564)
	... 41 common frames omitted